#push时候打招呼
name: not-pass
#触发事件：push
on: [push]

jobs:
    build:
        #作业名称greet
        name: greet
        #运行环境
        runs-on: windows-latest-not
        steps:
          - name: Echo time
            run: echo 'The time was ${{ steps.hello.outputs.time }}'
