#push时候打招呼
name: push-greet
#触发事件：push
on: [push]

jobs:
    job1:
        #作业名称greet
        name: greet-windows
        #运行环境
        runs-on: windows-latest
        steps:
          - name: hello
            uses: actions/hello-world-javascript-action@v1
            with:
                who-to-greet: "windows"
            id: hello
    
    job2:
        name: greet-macos
        runs-on: macos-latest
        steps:
          - name: "my-hello"
            uses: ts-zhang/hello-world-javascript-action@v1
            with:
                name: "macos"
            id: my-hello
    
    job3:
        name: linux-time
        runs-on: ubuntu-latest
        steps:
          - name: "current-time"
            run: echo 'The time was ${{ steps.hello.outputs.time }}'